name: build-image

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yml"
  pull_request:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yml"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [centos7, ubuntu22, rockylinux8]
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            tagModified:
              - 'Dockerfile.${{ matrix.tag }}'
              - 'entrypoint.sh'
              - ".github/workflows/build-image.yml"
      - if: steps.filter.outputs.tagModified == 'true'
        uses: docker/setup-qemu-action@v3
      - if: steps.filter.outputs.tagModified == 'true'
        uses: docker/setup-buildx-action@v3
      - if: steps.filter.outputs.tagModified == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - if: steps.filter.outputs.tagModified == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lp-prod:${{ matrix.tag }}
          file: Dockerfile.${{ matrix.tag }}
          platforms: linux/amd64
          progress: plain
          push: true
