name: build-image

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yml"
  pull_request:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yml"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [centos7, ubuntu22]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
      - run: |
          docker buildx build \
            --progress=plain \
            --platform linux/amd64 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/lp-prod:${{ matrix.tag }} \
            --file Dockerfile.${{ matrix.tag }} \
            --push \
            .
