name: build-image

on:
  workflow_dispatch:
  push:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yml"
  pull_request:
    paths:
      - "Dockerfile*"
      - "entrypoint.sh"
      - ".github/workflows/build-image.yml"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build the docker image and push
        run: |
          docker buildx create --use
          docker buildx build \
            --progress=plain \
            --platform linux/amd64 \
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/lp-prod:centos7 \
            --file Dockerfile.centos7 \
            --push \
            .
